config/routes.rb
# frozen_string_literal: true

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.htm
resources :timer_sessions, only: %i[index edit update patch destroy]

get 'timer_sessions_report', to: 'timer_sessions#report', as: :timer_sessions_report
get 'timer_sessions_time_error/:id', to: 'timer_sessions#time_error', as: :timer_sessions_time_error
post 'timer_sessions_rebalance/:id', to: 'timer_sessions#rebalance', as: :timer_sessions_rebalance
post 'timer_sessions_continue/:id', to: 'timer_sessions#continue', as: :timer_sessions_continue

# avoid resources because there is either 0 or 1 object
post :time_tracker, to: 'time_tracker#create'
patch :time_tracker, to: 'time_tracker#update'
delete :time_tracker, to: 'time_tracker#destroy'

get 'completion/issues', to: 'completion#issues'

match "/mcp" => "mcp#handle", via: [ :get, :post, :delete ]

app/models/timer_session.rb
# frozen_string_literal: true

class TimerSession < RedmineTrackyApplicationRecord
  has_many :timer_session_issues, dependent: :destroy
  has_many :timer_session_time_entries, dependent: :destroy

  belongs_to :user

  validates_with UnfinishedTimerSessionValidator
  validates_with FinishedTimerSessionValidator

  has_many :issues, -> { distinct }, through: :timer_session_issues
  has_many :time_entries, through: :timer_session_time_entries

  validates :timer_start, presence: true
  before_save :round_timer_to_nearest_minute
  before_save :set_recorded_hours

  scope :active, -> { where(finished: false) }
  scope :finished, -> { where(finished: true) }

  scope :created_by, ->(user) { where(user: user) }
  scope :recorded_on, ->(date) { where(timer_start: date) }

  attr_accessor :issue_id, :absolute_time

  def splittable_hours
    ((timer_end || Time.zone.now) - timer_start) / 1.hour
  end

  def session_finished?
    timer_end.present?
  end

  def recorded_hours
    time_entries.sum(:hours)
  end

  def relevant_issues
    if finished_was
      time_entries.includes(:issue).map(&:issue)
    else
      issues
    end
  end

  def overlaps?(other_session)
    return false unless can_overlap?(other_session)

    this_start = round_to_nearest_minute(timer_start)
    this_end = round_to_nearest_minute(timer_end)
    other_start = round_to_nearest_minute(other_session.timer_start)
    other_end = round_to_nearest_minute(other_session.timer_end)

    (this_start...this_end).overlaps?(other_start...other_end)
  end

  private

  def can_overlap?(other_session)
    return false if other_session.nil?
    return false if timer_start.nil? || timer_end.nil? || other_session.timer_start.nil? || other_session.timer_end.nil?

    true
  end

  def round_timer_to_nearest_minute
    self.timer_start = round_to_nearest_minute(timer_start) if timer_start.present?
    self.timer_end = round_to_nearest_minute(timer_end) if timer_end.present?
  end

  def round_to_nearest_minute(time)
    Time.at((time.to_f / 60).round * 60).utc
  end

  def set_recorded_hours
    return unless timer_start.present? && timer_end.present?

    self.hours = (timer_end - timer_start) / 1.hour
  end
end

app/controllers/timer_sessions_controller.rb
# frozen_string_literal: true

class TimerSessionsController < TrackyController
  def index
    @timer_sessions_in_range = TimerSession.includes(:time_entries, :timer_session_time_entries, issues: :project)
                                           .finished
                                           .created_by(User.current)
    @non_matching_timer_session_ids = TimeDiscrepancyLoader.uneven_timer_session_ids(@timer_sessions_in_range)
    set_timer_sessions
    @timer_offset = offset_for_time_zone
    @current_timer_session = TimerSession.active.find_by(user: User.current) || TimerSession.new
  end

  def report
    work_report_query = WorkReportQuery.new(report_query_params)
    result_url = WorkReportQueryBuilder.new(work_report_query).build_query
    redirect_to result_url
  end

  def time_entries_in_range(timer_sessions)
    time_entries = TimeEntry.where(user: User.current).includes(:project)
                            .where.not(id: timer_sessions.pluck(:'time_entries.id'))
    apply_filter(time_entries, :spent_on)
  end

  def rebalance
    @timer_session = user_scoped_timer_session(params[:id])
    TimeRebalancer.new(
      @timer_session.relevant_issues.map(&:id),
      @timer_session
    ).force_rebalance
    flash[:notice] = l(:notice_successful_update)
    redirect_to timer_sessions_path
  end

  def destroy
    timer_session = user_scoped_timer_session(params[:id])
    TimerEntityCleaner.new(timer_session).run
    timer_session.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to timer_sessions_path
  end

  def edit
    @timer_session = user_scoped_timer_session(params[:id])
    render_js :edit
  end

  def time_error
    @timer_session = TimeEntityDecorator.new(user_scoped_timer_session(params[:id]))
    render_js :time_error
  end

  def continue
    timer_session_template = user_scoped_timer_session(params[:id])
    linked_issues = timer_session_template.relevant_issues
    new_timer_session = timer_session_template.dup
    new_timer_session.update(timer_end: nil,
                             finished: false,
                             timer_start: (User.current.time_zone || Time.zone).now.asctime)
    IssueConnector.new(linked_issues.map(&:id) || [], new_timer_session).run
    redirect_to timer_sessions_path
  end

  def update
    @timer_session = user_scoped_timer_session(params[:id])
    if @timer_session.update(timer_session_params)
      TimeRebalancer.new(timer_session_params[:issue_ids],
                         @timer_session).rebalance_entries
      flash[:notice] = l(:notice_successful_update)
      render_js(@timer_session.valid? ? :update_redirect : :update)
    else
      render_js :update
    end
  end

  private

  def set_timer_sessions
    @timer_sessions = apply_filter(@timer_sessions_in_range, :timer_start)
    time_entries = time_entries_in_range(@timer_sessions)
    @timer_sessions = (@timer_sessions.order(timer_start: :desc) + time_entries)
                      .map { |time_entity| TimeEntityDecorator.new(time_entity) }
                      .sort_by(&:start_time)
                      .reverse
                      .group_by(&:entry_date)
  end

  def apply_filter(timer_sessions, column)
    @filter = Filtering::TimerSessionsFilter.new(filter_params.merge(filter_column: column))
    @filter.apply(timer_sessions)
  end

  def user_scoped_timer_session(id)
    TimerSession.where(user: User.current).find(id)
  end

  def timer_session_params
    params.require(:timer_session).permit(:comments,
                                          :timer_start,
                                          :timer_end,
                                          issue_ids: [])
  end

  def report_query_params
    params.require(:work_report_query).permit(:date, :period)
  end

  def filter_params
    return {} unless params[:filter].is_a?(ActionController::Parameters)

    params[:filter].permit(:min_date, :max_date).to_h
  end
end

app/helpers/timer_sessions_helper.rb
# frozen_string_literal: true

module TimerSessionsHelper
  include IconsHelper

  MAX_SUBJECT_LENGTH = 75
  SECONDS_IN_MINUTE = 60
  GAP_LIMIT_IN_MINUTES = 5

  def precision_for_display_hours
    SettingsManager.rounding_for_displayed_hours
  end

  def format_worked_hours(hours)
    "#{number_with_precision(hours, precision: precision_for_display_hours)} h"
  end

  def select_options_for_work_period
    WorkReportQuery::AVAILABLE_PERIODS
      .map do |period|
      I18n.t(period.to_s,
             scope: 'timer_sessions.work_report_query.periods')
    end
      .zip(
        WorkReportQuery::AVAILABLE_PERIODS
      )
  end

  def format_block_date(date)
    current_date = Time.zone.now.to_date
    if current_date == date || current_date.yesterday == date || current_date.tomorrow == date
      return I18n.t('timer_sessions.relative_times.tomorrow') if date == current_date.tomorrow
      return I18n.t('timer_sessions.relative_times.yesterday') if date == current_date.yesterday

      I18n.t('timer_sessions.relative_times.today')
    else
      I18n.l(date, format: I18n.t('timer_sessions.formats.date_with_year_and_weekday'))
    end
  end

  def format_time_entry_information(time_entry)
    issue = time_entry.issue
    issue_information = "##{issue.id}: #{issue.subject}"
    [
      issue_information,
      format_worked_hours(time_entry.hours)
    ].join(' - ')
  end

  def sum_work_hours(timer_sessions)
    total_hours = number_with_precision(
      timer_sessions
      .sum(&:recorded_hours),
      precision: precision_for_display_hours
    )
    I18n.t('timer_sessions.index.table.total_hours_worked', hours: total_hours)
  end

  def issue_information(issue)
    [
      issue_identifier(issue),
      issue.subject
    ].join(': ')
  end

  def issue_identifier(issue)
    "#{issue.id} #{issue.project.name}"
  end

  def draw_gap_separator(time_entity, previous_time_entity)
    return false if time_entity.nil? || previous_time_entity.nil?
    return false if !time_entity.timer_session? || !previous_time_entity.timer_session?

    ((time_entity.timer_start - previous_time_entity.timer_end) / SECONDS_IN_MINUTE) >= GAP_LIMIT_IN_MINUTES
  end

  def issue_link_list(issues)
    issues.map do |issue|
      link_to issue_information(issue), issue_path(issue)
    end
  end
end

app/views/timer_sessions/_edit_modal.html.erb
<div class="redmine-tracky" data-controller="issue-completion">
  <div class="edit-modal">
    <%= error_messages_for timer_session %>
    <%= labelled_form_for(timer_session, remote: true) do |f| %>
      <div class="row">
        <div class="update-issue-container">
          <div class="box">
            <%= render 'shared/ticker_issue_list', timer_session: timer_session, data_anker: 'data-update-issue-deletion-action', container_data_anker: 'data-update-issue-selection-container' %>
            <hr>
            <%= f.text_field :issue_id, label: false, id: 'timer_session_update_issue_id', type: :search, data: { issue_completion_target: 'input' } %>
            <% if SettingsManager.visible_hints %>
              <small class="form-text text-muted"><%= t('timer_sessions.messaging.issue_list_hint') %></small>
            <% end %>
          </div>
        </div>
      </div>
      <hr class="mb-3">
      <%= f.text_field :comments, data: { timer_update_comment_input: '' }, placeholder: t('timer_sessions.messaging.comments_placeholder') %>
      <br>
      <div class="times-container">
        <div class="col">
          <%= render 'shared/time_entry_input', f: f, input_name: :timer_start, value: timer_session.timer_start, required: true, target: 'start' %>
          <% if SettingsManager.visible_hints %>
            <small class="form-text text-muted"><%= t('timer_sessions.messaging.timer_start_hint') %></small>
          <% end %>
        </div>
        <br>
        <div class="col">
          <%= render 'shared/time_entry_input', f: f, input_name: :timer_end, value: timer_session.timer_end, required: true, target: 'end' %>
          <% if SettingsManager.visible_hints %>
            <small class="form-text text-muted"><%= t('timer_sessions.messaging.timer_end_hint') %></small>
          <% end %>
        </div>
      </div>
      <div class="mb-3"></div>
      <div class="buttons">
        <%= f.submit t('timer_sessions.edit.update'), data: { modal_update_button: '' } %>
        <br class="mt-3">
        <%= link_to_function l(:button_cancel), 'hideModal(this);', class: 'primary-cancel-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/timer_sessions/_entries_report_query.html.erb
<div class="box">
  <% current_report_query = current_report || WorkReportQuery.new %>
  <%= form_with model: current_report_query, url: timer_sessions_report_path, method: :get do |f| %>
    <%= f.date_field :date, value: Time.zone.now.to_date %>
    <%= f.select :period, select_options_for_work_period %>
    <div class="mt-3">
      <%= f.submit t('timer_sessions.work_report_query.buttons.submit') %>
    </div>
  <% end %>
</div>

app/views/timer_sessions/_sessions_filters.html.erb
<div class="box mb-3">
  <%= labelled_form_for @filter, as: :filter, url: timer_sessions_path, method: :get do |f| %>
    <div class="times-container">
      <div class="col">
        <%= f.date_field :min_date %>
      </div>
      <div class="col">
        <%= f.date_field :max_date %>
      </div>
    </div>
    <div class="mt-3">
      <%= f.submit t('timer_sessions.filters.filter') %>
    </div>
  <% end %>
</div>

app/views/timer_sessions/_time_discrepancy_modal.html.erb
<% base_scope = 'timer_sessions.messaging.errors.discrepancy_in_time_sum' %>
<h3><%= t('body', scope: base_scope, range: timer_session.formated_session_time) %></h3>
<div class="mt-3">
  <h4><%= t('resolution_options.options', scope: base_scope) %></h4>
  <ul>
    <li>
      <%= t('resolution_options.edit_timer_session', scope: base_scope, hours: format_worked_hours(timer_session.recorded_hours)) %><br>
      <%= link_to edit_timer_session_path(timer_session), remote: true do %>
        <%= t('timer_sessions.edit.title') %>
        <%= sprite_icon('edit', t(:button_edit), icon_only: true) %>
      <% end %>
    </li>
    <li>
      <%= t('resolution_options.edit_time_entries', scope: base_scope, hours: format_worked_hours(timer_session.splittable_hours)) %><br>
      <% if timer_session.time_entries.present? %>
        <% timer_session.time_entries.each do |time_entry| %>
          <ul>
            <li>
              <%= link_to edit_time_entry_path(time_entry) do %>
                <%= format_time_entry_information(time_entry) %>
                <%= sprite_icon('edit', t(:button_edit), icon_only: true) %>
              <% end %>
            </li>
          </ul>
        <% end %>
      <% else %>
        <b><%= t('timer_sessions.messaging.no_time_entries_found') %></b>
      <% end %>
    </li>
  </ul>
  <hr>
  <%= t('resolution_options.last_resort', scope: base_scope, hours: timer_session.recorded_hours) %>
  <div class="mt-3">
    <%= link_to timer_session_path(timer_session), data: { confirm: l(:text_are_you_sure) }, method: :delete, title: l(:button_delete) do %>
      <%= t('timer_sessions.destroy.button') %>
      <%= sprite_icon('del', t(:button_delete), icon_only: true) %>
    <% end %>
  </div>
  <div class="mt-3">
    <%= link_to timer_sessions_rebalance_path(timer_session), data: { confirm: l(:text_are_you_sure) }, method: :post, title: l(:button_delete) do %>
      <%= t('timer_sessions.rebalance.button') %>
      <%= sprite_icon('add', t(:button_add), icon_only: true) %>
    <% end %>
  </div>
</div>

app/views/timer_sessions/_timer_container.html.erb
<div class="box" data-controller="form timer" data-timer-timezone-value="<%= offset_for_time_zone %>">
  <div class="timer-container">
    <% active_timer_session = timer_session %>
    <%= labelled_form_for(active_timer_session,
      url: time_tracker_path,
      method: active_timer_session.persisted? ? :patch : :post,
      remote: true,
    ) do |f| %>
      <%= f.hidden_field :id, data: { timer_id: '' } %>
      <%= error_messages_for active_timer_session %>
      <% if active_timer_session.timer_start %>
        <div class="text-center mb-3">
          <div>
            <h1>
              <span id="hours-clock" class="left-text" data-timer-target="label">??:??</span>
            </h1>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="issue-container" data-controller="issue-completion">
          <div class="box">
            <%= render 'shared/ticker_issue_list', timer_session: active_timer_session,
                data_anker: 'data-issue-deletion-action', container_data_anker: 'data-issue-selection-container' %>
            <hr>
            <%= f.text_field :issue_id, label: false, type: :search, data: { issue_completion_target: 'input' },
                required: active_timer_session.persisted?, autofocus: 'autofocus' %>
            <% if SettingsManager.visible_hints %>
              <small class="form-text text-muted"><%= t('timer_sessions.messaging.issue_list_hint') %></small>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="col-12">
          <%= f.text_field :comments, data: { form_target: 'description', timer_target: 'description', action: 'change->form#change' },
              placeholder: t('timer_sessions.messaging.comments_placeholder'),
              required: active_timer_session.persisted?, class: 'w-100' %>
          <% if SettingsManager.visible_hints %>
            <small class="form-text text-muted"><%= t('timer_sessions.messaging.comments_hint') %></small>
          <% end %>
        </div>
      </div>
      <br>
      <div class="times-container">
        <div class="col">
          <div class="w-100">
            <%= render 'shared/time_entry_input', f: f, input_name: :timer_start, value: active_timer_session.timer_start, required: active_timer_session.persisted?, target: 'start' %>
            <% if SettingsManager.visible_hints %>
              <small class="form-text text-muted"><%= t('timer_sessions.messaging.timer_start_hint') %></small>
            <% end %>
          </div>
        </div>
        <br>
        <div class="col">
          <%= render 'shared/time_entry_input', f: f, input_name: :timer_end, value: active_timer_session.timer_end, required: active_timer_session.persisted?, target: 'end' %>
          <% if SettingsManager.visible_hints %>
            <small class="form-text text-muted"><%= t('timer_sessions.messaging.timer_end_hint') %></small>
          <% end %>
        </div>
      </div>
      <% if f.object.persisted? %>
        <%= f.text_field :absolute_time, class: 'w-100', data: { form_target: 'absolutInput', action: 'change->form#absoluteTime' }, placeholder: t('timer_sessions.timer.absolute_time_placeholder') %>
        <% if SettingsManager.visible_hints %>
          <small class="form-text text-muted"><%= t('timer_sessions.messaging.timer_absolute_time_hint') %></small>
        <% end %>
      <% end %>
      <div class="mb-3"></div>
      <% if timer_session.persisted? %>
        <div data-ending-action-buttons>
          <% if User.current.allowed_to_globally?(action: :update, controller: 'time_tracker') %>
            <%= f.button :stop, type: :submit, data: { name: 'timer-stop', form_target: 'stopButton' }, name: :stop do %>
              <%= t('timer_sessions.timer.stop') %>
            <% end %>
          <% end %>
          <% if User.current.allowed_to_globally?(action: :destroy, controller: 'time_tracker') %>
            <%= f.button :cancel, type: :submit, data: { name: 'timer-cancel', confirm: l(:text_are_you_sure) }, class: 'ml-3', name: :cancel, value: :cancel, form: "timer-cancel-form" do %>
              <%= t('timer_sessions.timer.cancel') %>
            <% end %>
          <% end %>
        </div>
      <% elsif !timer_session.persisted? && User.current.allowed_to_globally?(action: :create, controller: 'time_tracker') %>
        <%= f.button :start, type: :submit, value: :start, data: { name: 'timer-start' }, name: :commit do %>
          <%= t('timer_sessions.timer.start') %>
          <%= sprite_icon('add') %>
        <% end %>
        <%= f.button :start, type: :submit, value: :continue_last_session, data: { name: 'timer-continue' }, class: 'ml-3', name: :commit do %>
          <%= t('timer_sessions.timer.continue_last_session') %>
          <%= sprite_icon('add') %>
        <% end %>
      <% end %>
    <% end %>

    <%= button_to "", time_tracker_path, class: "hidden", method: :delete, form: {id: "timer-cancel-form", data: {remote: true}, format: "js"} %>
  </div>
</div>

app/views/timer_sessions/_timer_sessions_day_block.html.erb
<div class="box">
  <div class="space-between mb-3">
    <b><%= format_block_date(date) %></b>
    <b class="float-right"><%= sum_work_hours(Array.wrap(timer_sessions)) %></b>
  </div>

  <table class="list timer-sessions-table table-fixed">
    <tbody>
      <% timer_sessions.each_with_index do |time_entity, index| %>
        <% previous_time_entity = timer_sessions[index + 1] %>
        <%= render TimerSessionEntryComponent.new(
          timer_session_entry: time_entity,
          discrepancy_detected: @non_matching_timer_session_ids.include?(time_entity.id),
          overlap_detected: timer_sessions.any? do |other_entity|
            other_entity.timer_session? && 
            time_entity.timer_session? && 
            time_entity != other_entity && 
            other_entity.overlaps?(time_entity)
          end,
          gap_separator: draw_gap_separator(time_entity, previous_time_entity)
        ) %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/timer_sessions/_timer_sessions_list.html.erb
<%= render 'sessions_filters' %>
<% timer_sessions_by_day.to_a.each do |date, timer_session_day| %>
  <%= render 'timer_sessions_day_block',
    date: date,
    timer_sessions: timer_session_day %>
<% end %>

app/views/timer_sessions/edit.js.erb
$('#ajax-modal').html(
  ("<%= j render 'edit_modal', timer_session: @timer_session %>")
);

showModal('ajax-modal', '800px', '<%= t('timer_sessions.edit.title') %>');
$('#ajax-modal').addClass('new-watcher');

app/views/timer_sessions/index.html.erb
<div class="redmine-tracky">
  <div class="w-75 mx-auto">
    <h1 class="text-center"><%= t('timer_sessions.index.title') %></h1>
    <div class="w-100 mt-3" data-timer-session-container>
      <%= render 'timer_container', timer_session: @current_timer_session %>
    </div>
    <hr>
    <div class="w-100" data-timer-sessions-list>
      <%= render 'timer_sessions_list', timer_sessions_by_day: @timer_sessions %>
    </div>
    <% if User.current.allowed_to_globally?(action: :report, controller: 'timer_sessions') %>
      <hr>
      <div class="w-100" data-timer-session-container>
        <%= render 'entries_report_query', current_report: @current_report %>
      </div>
    <% end %>
    <%= render 'shared/assets' %>
  </div>
</div>

app/views/timer_sessions/time_error.js.erb
$('#ajax-modal').html(
  ("<%= j render 'time_discrepancy_modal', timer_session: @timer_session %>")
);

showModal('ajax-modal', '800px', '<%= t('timer_sessions.messaging.errors.discrepancy_in_time_sum.title') %>');
$('#ajax-modal').addClass('new-watcher');

app/views/timer_sessions/update.js.erb
<% @timer_session.validate %>
$('#ajax-modal').html(
  ("<%= j render 'edit_modal', timer_session: @timer_session %>")
);

showModal('ajax-modal', '800px', '<%= t('timer_sessions.edit.title') %>');
$('#ajax-modal').addClass('new-watcher');

app/views/timer_sessions/update_redirect.js.erb
window.location.href = '<%= timer_sessions_path %>' + window.location.search;