config/routes.rb
# frozen_string_literal: true

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.htm
resources :timer_sessions, only: %i[index edit update patch destroy]

get 'timer_sessions_report', to: 'timer_sessions#report', as: :timer_sessions_report
get 'timer_sessions_time_error/:id', to: 'timer_sessions#time_error', as: :timer_sessions_time_error
post 'timer_sessions_rebalance/:id', to: 'timer_sessions#rebalance', as: :timer_sessions_rebalance
post 'timer_sessions_continue/:id', to: 'timer_sessions#continue', as: :timer_sessions_continue

# avoid resources because there is either 0 or 1 object
post :time_tracker, to: 'time_tracker#create'
patch :time_tracker, to: 'time_tracker#update'
delete :time_tracker, to: 'time_tracker#destroy'

get 'completion/issues', to: 'completion#issues'

match "/mcp" => "mcp#handle", via: [ :get, :post, :delete ]

app/models/timer_session.rb
# frozen_string_literal: true

class TimerSession < RedmineTrackyApplicationRecord
  has_many :timer_session_issues, dependent: :destroy
  has_many :timer_session_time_entries, dependent: :destroy

  belongs_to :user

  validates_with UnfinishedTimerSessionValidator
  validates_with FinishedTimerSessionValidator

  has_many :issues, -> { distinct }, through: :timer_session_issues
  has_many :time_entries, through: :timer_session_time_entries

  validates :timer_start, presence: true
  before_save :round_timer_to_nearest_minute
  before_save :set_recorded_hours

  scope :active, -> { where(finished: false) }
  scope :finished, -> { where(finished: true) }

  scope :created_by, ->(user) { where(user: user) }
  scope :recorded_on, ->(date) { where(timer_start: date) }

  attr_accessor :issue_id, :absolute_time

  def splittable_hours
    ((timer_end || Time.zone.now) - timer_start) / 1.hour
  end

  def session_finished?
    timer_end.present?
  end

  def recorded_hours
    time_entries.sum(:hours)
  end

  def relevant_issues
    if finished_was
      time_entries.includes(:issue).map(&:issue)
    else
      issues
    end
  end

  def overlaps?(other_session)
    return false unless can_overlap?(other_session)

    this_start = round_to_nearest_minute(timer_start)
    this_end = round_to_nearest_minute(timer_end)
    other_start = round_to_nearest_minute(other_session.timer_start)
    other_end = round_to_nearest_minute(other_session.timer_end)

    (this_start...this_end).overlaps?(other_start...other_end)
  end

  private

  def can_overlap?(other_session)
    return false if other_session.nil?
    return false if timer_start.nil? || timer_end.nil? || other_session.timer_start.nil? || other_session.timer_end.nil?

    true
  end

  def round_timer_to_nearest_minute
    self.timer_start = round_to_nearest_minute(timer_start) if timer_start.present?
    self.timer_end = round_to_nearest_minute(timer_end) if timer_end.present?
  end

  def round_to_nearest_minute(time)
    Time.at((time.to_f / 60).round * 60).utc
  end

  def set_recorded_hours
    return unless timer_start.present? && timer_end.present?

    self.hours = (timer_end - timer_start) / 1.hour
  end
end

app/views/shared/_assets.html.erb
<%= render 'shared/js_variables' %>
<%= javascript_include_tag "redmine-tracky.js", type: "module", plugin: 'redmine_tracky' %>

app/views/shared/_js_variables.html.erb
<script>
  var RedmineTracky = RedmineTracky || {};
  RedmineTracky.datetimeFormat = "<%= j(I18n.t('timer_sessions.formats.jquery_datetime_format')) %>";
  RedmineTracky.issueCompletionPath = "<%= j(completion_issues_path) %>";
  RedmineTracky.trackerUpdatePath = "<%= j(time_tracker_path) %>";
  RedmineTracky.datetimeFormatJavascript = "<%= j(I18n.t('timer_sessions.formats.js_datetime_format')) %>";
  RedmineTracky.documentTitle = "<%= j(I18n.t('timer_sessions.index.title')) %>";
</script>

app/views/shared/_ticker_issue_list.html.erb
<div data-controller="list" data-issue-completion-target="listAnchor">
  <table data-list-target="table">
    <template>
      <%= render "shared/ticker_issue_list_entry", issue: Issue.new(id: 0) %>
    </template>
    <tbody>
      <% timer_session.relevant_issues.each do |issue| %>
        <%= render "shared/ticker_issue_list_entry", issue: issue %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_ticker_issue_list_entry.html.erb
<tr class="issue-container" data-form-target="issue" data-issue-id="<%= issue.id %>">
  <td>
    <b><%= link_to "#{issue.project} - #{issue.id}:", issue_path(issue.id), target: :_blank, rel: :noopener %></b>
  </td>
  <td data-issue-subject><%= issue.subject %></td>
  <td>
    <span class="text-danger input-group-text" data-action="click->list#removeItem">
      <%= sprite_icon('del', t(:button_delete), icon_only: true) %>
    </span>
    <%= hidden_field_tag 'timer_session[issue_ids][]', issue.id,
                         id: "timer_session_issue_id_#{issue.id}", readonly: true %>
  </td>
</tr>

app/views/shared/_time_entry_input.html.erb
<%= f.text_field input_name, class: 'w-100', data: { controller: 'flatpickr', form_target: target, action: 'change->form#change', flatpickr_date_format: "d.m.Y H:i", flatpickr_minute_Increment: 1, flatpickr_enable_time: true, flatpickr_time_24hr: true, flatpickr_allow_input: true, timer_target: target}, placeholder: t('timer_sessions.timer.date_placeholder'), required: required, value: value&.strftime(t('timer_sessions.formats.datetime_format')) %>